### ISSUE TITLE
Add more testcases

### ISSUE THREAD

**Issue by SeriousM** [envkey/envkey-fetch#7]
Hi. Would it be possible to add more teststrings to the envkey?
My own teststrings are this:

```
{"SECRET_SPECIAL":"another secret","SPECIAL_SECRET":"special secret key","STRANGE\"\"KEY":"with quotes ` ' \" bäh"}
```

This way i'm able to check for very special cases.

https://github.com/envkey/envkey-fetch/blob/fa2abef676c6a2927f98d518df06a189b3c881e9/fetch/fetch_test/fetch_test.go#L137

**Comment by danenania** [comment]
Hi @SeriousM, yeah adding the  ```"with quotes ` ' \" bäh"``` test case sounds like a good idea, except that really I don't want to encourage keys that aren't valid environment variables like `"STRANGE\"\"KEY"`, since they will break when using [envkey-source](https://github.com/envkey/envkey-source). Keys like that should probably be rejected by the client.
